[package]
name          = "serde_json"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = "JSON serialization"

[lib]

[scripts]
test = { workspace = true }

[dependencies]
ibc_utils = { workspace = true }

[dev-dependencies]
assert_macros = { workspace = true }
snforge_std   = { workspace = true }

[tool]
fmt   = { workspace = true }
scarb = { workspace = true }
