[package]
name          = "starknet_ibc_testkit"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = "Common artifacts for testing IBC packages"

[lib]

[scripts]
test = { workspace = true }

[tool]
fmt   = { workspace = true }
scarb = { workspace = true }

[dependencies]
# external dependencies
openzeppelin_access  = { workspace = true }
openzeppelin_testing = { workspace = true }
openzeppelin_utils   = { workspace = true }
openzeppelin_token   = { workspace = true }
starknet             = { workspace = true }

# internal dependencies
ics23    = { workspace = true }
protobuf = { workspace = true }

# ibc dependencies
starknet_ibc_core    = { workspace = true }
starknet_ibc_clients = { workspace = true }
starknet_ibc_apps    = { workspace = true }

cometbft = { workspace = true }

serde_json  = { workspace = true }
snforge_std = { workspace = true }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra                     = true
casm                       = false
