[package]
name          = "starknet_ibc_testkit"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }

description = """
    Provides a set of common artifacts used for testing different IBC packages.
"""

[lib]

[scripts]
test = { workspace = true }

[tool]
fmt = { workspace = true }

[dependencies]
# external dependencies
openzeppelin_access  = { workspace = true }
openzeppelin_testing = { workspace = true }
openzeppelin_utils   = { workspace = true }
starknet             = { workspace = true }

# ibc dependencies
starknet_ibc_core    = { workspace = true }
starknet_ibc_clients = { workspace = true }
starknet_ibc_apps    = { workspace = true }
