[package]
name    = "madara_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet           = "2.12.2"
cairo_test         = "2.12.2"
openzeppelin_token = "2.0.0"

[dev-dependencies]

[[target.starknet-contract]]
sierra = true
