[package]
name    = "protobuf"
version = "0.1.0"
edition = { workspace = true }

[lib]

[scripts]
test = { workspace = true }

[dependencies]

[dev-dependencies]
alexandria_math = { workspace = true }
cairo_test      = { workspace = true }
snforge_std     = { workspace = true }
