[package]
name    = "protobuf"
version = "0.1.0"
edition = { workspace = true }

[lib]

[scripts]
test = { workspace = true }

[tool]
fmt   = { workspace = true }
scarb = { workspace = true }

[dependencies]
ibc_utils = { workspace = true }

[dev-dependencies]
alexandria_math = { workspace = true }
assert_macros   = { workspace = true }
snforge_std     = { workspace = true }
