[workspace]
members = [
  "packages/protobuf",
  "packages/cometbft",
  "packages/serde_json",
  "packages/ics23",
]

[workspace.package]
version       = "0.1.0"
edition       = "2024_07"
cairo-version = "2.11.2"
scarb-version = "2.11.3"
license       = "Apache-2.0"
authors       = [ "Informal Systems <hello@informal.systems>" ]
repository    = "https://github.com/informalsystems/ibc-starknet"
Readme        = "README.md"
keywords      = [ "protobuf", "cometbft", "ibc" ]
description   = "Cairo libraries for integrating Starknet with IBC"

[workspace.scripts]
test = "snforge test"

[workspace.dependencies]
# external dependencies
starknet        = "2.11.2"
assert_macros   = "2.11.2"
snforge_std     = "0.39.0"
alexandria_math = "0.5.0"

# internal dependencies
protobuf = { path = "packages/protobuf" }
ics23    = { path = "packages/ics23" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = [ "snforge_std" ]
