[workspace]
members = [
  "packages/protobuf",
  "packages/cometbft",
  "packages/serde_json",
  "packages/ics23",
]

[workspace.package]
version       = "0.1.0"
edition       = "2024_07"
cairo-version = "2.11.4"
scarb-version = "2.11.4"
license       = "Apache-2.0"
authors       = [ "Informal Systems <hello@informal.systems>" ]
repository    = "https://github.com/informalsystems/ibc-starknet"
Readme        = "README.md"
keywords      = [ "protobuf", "cometbft", "ibc" ]
description   = "Cairo libraries for integrating Starknet with IBC"

[workspace.scripts]
test = "snforge test"

[workspace.dependencies]
starknet      = "2.11.4"
assert_macros = "2.11.4"
snforge_std   = "0.41.0"

# external dependencies
# FIXME: using main branch for ed25519 signature fix
# use release version from scarbs.xyz
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria" }

# internal dependencies
protobuf = { path = "packages/protobuf" }
ics23    = { path = "packages/ics23" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = [ "snforge_std" ]
