[workspace]
members = [
  "packages/protobuf",
  "packages/cometbft",
  "packages/serde_json",
  "packages/ics23",
  "packages/ibc_utils",
]

[workspace.package]
version       = "0.1.0"
edition       = "2024_07"
cairo-version = "2.11.4"
scarb-version = "2.11.4"
license       = "Apache-2.0"
authors       = [ "Informal Systems <hello@informal.systems>" ]
repository    = "https://github.com/informalsystems/ibc-starknet"
Readme        = "README.md"
keywords      = [ "protobuf", "cometbft", "ibc" ]
description   = "Cairo libraries for integrating Starknet with IBC"

[workspace.scripts]
test = "snforge test"

[workspace.dependencies]
starknet      = "2.11.4"
assert_macros = "2.11.4"
snforge_std   = "0.44.0"

# external dependencies
alexandria_math = { version = "0.5.1" }
garaga          = { git = "https://github.com/keep-starknet-strange/garaga.git" }

# internal dependencies
protobuf  = { path = "packages/protobuf" }
ics23     = { path = "packages/ics23" }
ibc_utils = { path = "packages/ibc_utils" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = [ "snforge_std" ]
