[workspace]
members = [
  "packages/protobuf",
  "packages/cometbft",
  "packages/serde_json",
  "packages/ics23",
]

[workspace.package]
version       = "0.1.0"
edition       = "2024_07"
cairo-version = "2.8.4"
scarb-version = "2.8.4"
license       = "Apache-2.0"
authors       = [ "Informal Systems <hello@informal.systems>" ]
repository    = "https://github.com/informalsystems/ibc-starknet"
Readme        = "README.md"
keywords      = [ "protobuf", "cometbft", "ibc" ]
description   = "Collection of Cairo libraries for IBC integration with Starknet"

[workspace.scripts]
test = "snforge test"

[workspace.dependencies]
# external dependencies
alexandria_numeric = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "95d98a5" }
assert_macros      = "2.8.4"
cairo_test         = "2.8.4"
starknet           = "2.8.4"
snforge_std        = "0.31.0"

# internal dependencies
protobuf = { path = "packages/protobuf" }
ics23    = { path = "packages/ics23" }

[workspace.tool.fmt]
sort-module-level-items = true
