[package]
name    = "cometbft"
version = "0.1.0"
edition = { workspace = true }

[lib]

[scripts]
test = { workspace = true }

[tool]
fmt   = { workspace = true }
scarb = { workspace = true }

[dependencies]
starknet        = { workspace = true }
alexandria_math = { workspace = true }
garaga          = { workspace = true }
protobuf        = { workspace = true }
ics23           = { workspace = true }
ibc_utils       = { workspace = true }

[dev-dependencies]
assert_macros = { workspace = true }
snforge_std   = { workspace = true }
