[package]
name    = "cometbft"
version = "0.1.0"
edition = { workspace = true }

[lib]

[scripts]
test = { workspace = true }

[dependencies]
protobuf = { path = "../protobuf" }

[dev-dependencies]
snforge_std = { workspace = true }
