[package]
name    = "cometbft"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
protobuf = { path = "../protobuf" }

[dev-dependencies]
cairo_test  = { workspace = true }
snforge_std = { workspace = true }
