[workspace]
members = [
    "crates/ibc-components",
]

[workspace.package]
version       = "0.1.0"
license       = "Apache-2.0"
edition       = "2023_11"
cairo-version = "2.8.0"
scarb-version = "2.8.0"
repository    = "https://github.com/informalsystems/ibc-starknet"
authors       = [ "Informal Systems <hello@informal.systems>" ]
Readme        = "README.md"
keywords      = [ "ethereum", "starknet", "ibc", "cairo", "contracts" ]
description   = "Collection of Cairo components and contracts that implement and integrate IBC protocol with Starknet"

[workspace.dependencies]
# external dependencies
# starknet     = ">=2.8.0"
cairo_test = "2.8.0"
starknet_ibc_components = { version = "0.1.0", path = "./crates/ibc-components" }

# ibc dependencies

[workspace.tool.fmt]
sort-module-level-items = true

# [package]
# name = "starknet_ibc"
# version.workspace = true

# [lib]

# [dependencies]
# starknet_ibc_components = { workspace = true }
