[package]
name          = "ics23"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = "ICS-23 vector commitments"

[lib]

[scripts]
test = { workspace = true }

[tool]
fmt   = { workspace = true }
scarb = { workspace = true }

[dependencies]
protobuf = { workspace = true }
starknet = { workspace = true }

[dev-dependencies]
assert_macros = { workspace = true }
snforge_std   = { workspace = true }
