[package]
name          = "starknet_ibc_clients"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = "IBC client contracts for Starknet"

[lib]

[scripts]
test = { workspace = true }

[tool]
fmt = { workspace = true }

[dependencies]
alexandria_data_structures = { workspace = true }
alexandria_sorting         = { workspace = true }
openzeppelin_access        = { workspace = true }
snforge_std                = { workspace = true }

# external dependencies
starknet = { workspace = true }

# ibc dependencies
starknet_ibc_core  = { workspace = true }
starknet_ibc_utils = { workspace = true }

[dev-dependencies]
starknet_ibc_testkit = { workspace = true }
