[package]
name          = "starknet_ibc_presets"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = { workspace = true }

[dependencies]
# external dependencies
starknet            = { workspace = true }
openzeppelin_access = { workspace = true }
openzeppelin_token  = { workspace = true }

# ibc dependencies
starknet_ibc_utils   = { workspace = true }
starknet_ibc_core    = { workspace = true }
starknet_ibc_clients = { workspace = true }
starknet_ibc_apps    = { workspace = true }

[lib]

[tool]
fmt = { workspace = true }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra                     = true
casm                       = false
