[package]
name          = "starknet_ibc_core_channel"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = { workspace = true }

[dependencies]
# external dependencies
starknet    = { workspace = true }
snforge_std = { workspace = true }

# ibc dependencies
starknet_ibc_core_host   = { workspace = true }
starknet_ibc_core_client = { workspace = true }

[lib]

[tool]
fmt = { workspace = true }
