name: Cairo Libs and Contracts
on:
  pull_request:
    paths:
      - cairo-libs/**
      - cairo-contracts/**
      - .github/workflows/cairo.yaml
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main

jobs:
  test-cairo-libs:
    name: Test Cairo libraries
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: cairo-libs/.tool-versions
          scarb-lock: cairo-libs/Scarb.lock

      - name: Install Universal Sierra Compiler
        uses: software-mansion/setup-universal-sierra-compiler@v1
        with:
          tool-versions: cairo-libs/.tool-versions

      - name: Install Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: cairo-libs/.tool-versions

      - name: Build and Test Cairo libraries
        working-directory: ./cairo-libs
        run: |
          scarb build -w
          scarb lint -w
          scarb test -w

  test-cairo-contracts:
    name: Test Cairo contracts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: cairo-contracts/.tool-versions
          scarb-lock: cairo-contracts/Scarb.lock

      - name: Install Universal Sierra Compiler
        uses: software-mansion/setup-universal-sierra-compiler@v1
        with:
          tool-versions: cairo-contracts/.tool-versions

      - name: Install Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: cairo-contracts/.tool-versions

      - name: Build and Test Cairo contracts
        working-directory: ./cairo-contracts
        run: |
          scarb build -w
          scarb build -p starknet_ibc_contracts
          scarb lint -w
          scarb test -w
