name: MacOS Build
on:
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main

jobs:
  test-contracts:
    name: Build Nix dependencies
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v15
        with:
          name: ibc-starknet
          extraPullNames: hermes-sdk,cosmos-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Remove Homebrew
        if: ${{ matrix.os == 'macos-14' }}
        run: |
          sudo rm -rf /opt/homebrew

      - name: Run Nix build
        run: |
          nix develop -c true
